---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=develop
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        stages: [manual]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
        args:
          - --fix
          - --ignore=E501
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --quiet
        files: ^((custom_components.*?|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
          - -L=hass
        exclude_types: [csv, json]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
        files: ^(custom_components.*)/.+\.py$
        exclude: .*/tests/.+\.py$
  - repo: https://github.com/PyCQA/pylint
    rev: "v2.16.3"
    hooks:
      - id: pylint
        additional_dependencies:
          ["homeassistant>=1.9.3", "portlandgeneral-api>=1.1.0"]
        files: ^(custom_components.*)/.+\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle==2.10.0
          - pyflakes==3.0.1
          - flake8-docstrings==1.6.0
          - pydocstyle==6.2.3
          - flake8-comprehensions==3.10.1
          - flake8-noqa==1.3.0
          - mccabe==0.7.0
        exclude: docs/source/conf.py
        stages: [manual]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-unittest
        stages: [commit]
        types: [python]
        entry: python -m pytest tests -p pytest_cov --cov=./custom_components --cov-config=.coveragerc --durations=0 -sv -n auto
        language: system
        pass_filenames: false
        always_run: true
